# Build Sol Dataset

## Install necessary libraries from python

In [8]:
# import os

# src = "/kaggle/input/sc-vuldetection-dataset/SmartContractVulnerabilityDetection/SourceCodeSyntaxDataset/TimestampDependencyDataset/Train/Vulnerable"

# cnt = 0
# for file in os.listdir(src):
#     with open(src + "/" + file, "r") as f:
#         data = f.read()
#     if "block.timestamp" in data or "now" in data:
#         cnt =+ 1

# print(cnt)

In [9]:
# Use Gpu
!pip install dgl==2.0.0 -f https://data.dgl.ai/wheels/cu121/repo.html
# Only use cpu
# !pip install dgl==1.1.2

Looking in links: https://data.dgl.ai/wheels/cu121/repo.html
Collecting dgl==2.0.0
  Downloading https://data.dgl.ai/wheels/cu121/dgl-2.0.0%2Bcu121-cp310-cp310-manylinux1_x86_64.whl (926.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 926.0/926.0 MB 1.3 MB/s eta 0:00:00:00:0100:01m
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from dgl==2.0.0) (1.26.4)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from dgl==2.0.0) (1.13.1)
Requirement already satisfied: networkx>=2.1 in /usr/local/lib/python3.10/dist-packages (from dgl==2.0.0) (3.4.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from dgl==2.0.0) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from dgl==2.0.0) (4.67.1)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.10/dist-packages (from dgl==2.0.0) (5.9.5)
Collecting torchdata>=0.5.0 (from dgl==2.0.0)
  Downloading torchdata-0.11.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->dgl==2.0.0) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->dgl==2.0.0) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->dgl==2.0.0) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->dgl==2.0.0) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->dgl==2.0.0) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy>=1.14.0->dgl==2.0.0) (2.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl==2.0.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl==2.0.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl==2.0.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->dgl==2.0.0) (2025.1.31)
Requirement already satisfied: torch>=2 in /usr/local/lib/python3.10/dist-packages (from torchdata>=0.5.0->dgl==2.0.0) (2.5.1+cu121)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=2->torchdata>=0.5.0->dgl==2.0.0) (3.17.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2->torchdata>=0.5.0->dgl==2.0.0) (4.12.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2->torchdata>=0.5.0->dgl==2.0.0) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=2->torchdata>=0.5.0->dgl==2.0.0) (2024.12.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=2->torchdata>=0.5.0->dgl==2.0.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=2->torchdata>=0.5.0->dgl==2.0.0) (1.3.0)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.14.0->dgl==2.0.0) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy>=1.14.0->dgl==2.0.0) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy>=1.14.0->dgl==2.0.0) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy>=1.14.0->dgl==2.0.0) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy>=1.14.0->dgl==2.0.0) (2024.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2->torchdata>=0.5.0->dgl==2.0.0) (3.0.2)
Downloading torchdata-0.11.0-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.8 MB/s eta 0:00:00
Installing collected packages: torchdata, dgl
Successfully installed dgl-2.0.0+cu121 torchdata-0.11.0

In [10]:
%%capture
# !apt install libgraphviz-dev
# !pip install pygraphviz
!pip install networkx
!pip install slither-analyzer

## Import Python libraries

In [11]:
from concurrent.futures import ThreadPoolExecutor
from random import sample
import json
import multiprocessing
import traceback
import pandas as pd
import os
from pathlib import Path
import networkx as nx
# import pygraphviz as pgv
import matplotlib.pyplot as plt
import nltk
import dgl
import os
import shutil
import random
from slither.slither import Slither
from typing import Tuple, Optional, Dict
from copy import deepcopy
from pathlib import Path
import glob
from multiprocessing import Pool as ThreadPool
from functools import partial
import torch.nn as nn
import torch
from torch import Tensor
import torch.nn.functional as F
from dgl.nn import GraphConv, GATConv, TAGConv, SAGEConv, GINConv, SumPooling, AvgPooling, MaxPooling, SortPooling, GlobalAttentionPooling, WeightAndSum, Set2Set, SetTransformerEncoder, SetTransformerDecoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
import pickle
import random
import numpy as np
from tqdm import tqdm

DGL backend not selected or invalid.  Assuming PyTorch for now.

Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)

# Functions

In [12]:
def plot(x: list, y: list):
  x = np.array(x)
  y = np.array(y)

  plt.plot(x, y)
  plt.title("Decrease of loss over epochs")
  plt.xlabel("Epochs")
  plt.ylabel("Loss")
  plt.show()

In [13]:
def readData(path: str, n_nscam: int, n_scam: int):
  dic = {
      "filename": [],
      "label": []
  }
  cnt0, cnt1 = 0, 0
  for label in ["NonVulnerable_Fcg", "Vulnerable_Fcg"]:
    for file in sorted(os.listdir(path + "/" + label)):
      if file.endswith(".fcg"):
        if label == "NonVulnerable_Fcg":
          if cnt0 <= n_nscam:
            dic['filename'].append("/".join([path, label, file]))
            dic['label'].append(0)
            cnt0 += 1
        else:
          if cnt1 <= n_scam:
            dic['filename'].append("/".join([path, label, file]))
            dic['label'].append(1)
            cnt1 += 1
  df = pd.DataFrame(dic)
  return df

In [14]:
def loadfeatureGraph_5(path):
  """
    path: path to fcg file

    return: dgl.DGLGraph with feature size of 5
  """
  g = dgl.load_graphs(path)[0][0]
  return g

def loadfeatureGraph_100(path):
  """
    path: path to fcg file

    return: dgl.DGLGraph with feature size of 100
  """
  g = dgl.load_graphs(path)[0][0]
  g.ndata["features"] = g.ndata["featuresH"]
  return g

def loadfeatureGraph_105(path):
  """
    path: path to fcg file

    return: dgl.DGLGraph with feature size of 105
  """
  g = dgl.load_graphs(path)[0][0]
  template = g.ndata["features"]

  g.ndata["features"] = torch.cat([g.ndata["featuresH"], template], dim=1)
  return g

def createBatchMulThread_MultiOp(data, max_works, nfeatures):
  """
    data: Graph paths,
    nfeatures: Size of node feature
    max_works: number of thread use

    return list[DGLGraph]
  """
  pathfiles = data
  if nfeatures == 5:
    with ThreadPoolExecutor(max_works) as executor:
      graphs = list(executor.map(loadfeatureGraph_5, pathfiles))
  elif nfeatures == 768:
    with ThreadPoolExecutor(max_works) as executor:
      graphs = list(executor.map(loadfeatureGraph_100, pathfiles))
  elif nfeatures == 773:
    with ThreadPoolExecutor(max_works) as executor:
      graphs = list(executor.map(loadfeatureGraph_105, pathfiles))
  return graphs

# Model GNNs

In [52]:
import dgl.nn.pytorch as dglnn
import torch.nn as nn
from copy import deepcopy as dc

#---------------------------------------------------------------------------------------------------------------------
class MultiHeadCrossAttentionPooling(nn.Module):
    def __init__(self, hidden_dim, num_query_vectors=1, num_heads=4):
        super(MultiHeadCrossAttentionPooling, self).__init__()
        self.num_query_vectors = num_query_vectors
        self.hidden_dim = hidden_dim
        self.num_heads = num_heads
        
        # Single set of query vectors, will be reshaped for multi-head
        self.query = nn.Parameter(torch.randn(num_query_vectors, hidden_dim))
        
        # Single transformations that will be reshaped for multi-head attention
        self.key_transform = nn.Linear(hidden_dim, hidden_dim)
        self.value_transform = nn.Linear(hidden_dim, hidden_dim)
        
        # Output projection
        self.output_projection = nn.Linear(hidden_dim, hidden_dim)
        
        # Final output dimension
        self.output_dim = hidden_dim * num_query_vectors
        
    def forward(self, g, h):
        graph_splits = g.batch_num_nodes()
        batch_size = len(graph_splits)
        device = h.device
        output = torch.zeros(batch_size, self.output_dim, device=device)
        
        # Transform once for all heads
        keys = self.key_transform(h)      # (total_nodes x hidden_dim)
        values = self.value_transform(h)   # (total_nodes x hidden_dim)
        
        # Reshape for multi-head attention
        # Reshape to: [num_nodes, num_heads, hidden_dim/num_heads]
        keys = keys.view(-1, self.num_heads, self.hidden_dim // self.num_heads)
        values = values.view(-1, self.num_heads, self.hidden_dim // self.num_heads)
        query = self.query.view(self.num_query_vectors, self.num_heads, -1)
        
        start_idx = 0
        for i, num_nodes in enumerate(graph_splits):
            end_idx = start_idx + num_nodes
            
            # Get current graph's nodes
            graph_keys = keys[start_idx:end_idx]    # (num_nodes x num_heads x head_dim)
            graph_values = values[start_idx:end_idx] # (num_nodes x num_heads x head_dim)
            
            # Calculate attention scores (for all heads simultaneously)
            scores = torch.matmul(query.permute(1, 0, 2), graph_keys.permute(1, 2, 0))
            # scores shape: [num_heads, num_queries, num_nodes]
            
            attention_weights = F.softmax(scores / (self.hidden_dim // self.num_heads) ** 0.5, dim=-1)
            
            # Apply attention
            head_outputs = torch.matmul(attention_weights, graph_values.permute(1, 0, 2))
            # head_outputs shape: [num_heads, num_queries, head_dim]
            
            # Concatenate heads and reshape
            multi_head_output = head_outputs.permute(1, 0, 2).reshape(self.num_query_vectors, -1)
            
            # Project output
            projected_output = self.output_projection(multi_head_output)
            
            # Store result
            output[i] = projected_output.reshape(-1)
            
            start_idx = end_idx
        
        return output
#---------------------------------------------------------------------------------------------------------------------

def get_convolution_layer(
            input_dimension: int,
            output_dimension: int,
            name: list,
            agg_hidden_dimension: int = 1024, # Only use for GINConv
            heads: int = 0 # Only use for GATConv
    ) -> Optional[nn.Module]:
        mlp, gin_agg, sage_agg = None, 'sum', 'mean'
        if name[0] == "GIN":
          mlp = nn.Sequential()
          mlp.append(nn.Linear(input_dimension, agg_hidden_dimension))
          mlp.append(nn.ReLU())
          mlp.append(nn.Linear(agg_hidden_dimension, output_dimension))
          gin_agg = name[1]

        if name[0] == "SAGE":
          sage_agg = name[1]

        return {"GCN": GraphConv(input_dimension, output_dimension, activation=F.relu),
                "SAGE": SAGEConv(input_dimension, output_dimension, activation=F.relu, norm=F.normalize, aggregator_type=sage_agg),
                "GAT": GATConv(input_dimension, output_dimension, num_heads=heads, activation=F.relu, feat_drop=0.0, attn_drop=0.0),
                "TAG": TAGConv(input_dimension, output_dimension, k=4, activation=F.relu),
                "GIN": GINConv(apply_func=mlp, activation=F.relu, aggregator_type=gin_agg)
                }.get(name[0], None)

def get_pooling_method(
            method_name: str,
            hidden_dim: int = None  # Add hidden_dim parameter
    ):
        return {"max": MaxPooling(),
                "mean": AvgPooling(),
                "sum": SumPooling(),
                "sort": SortPooling(k=3),
                "transformer": (SetTransformerEncoder(5, 4, 4, 20), SetTransformerDecoder(5, 4, 4, 20, 1, 3)),
                "global_attention": GlobalAttentionPooling(gate_nn=nn.Linear(hidden_dim, 1),
                                                         feat_nn=nn.Linear(hidden_dim, hidden_dim))
                }.get(method_name, None)

class GraphNN(nn.Module):
    def __init__(self, mtype, infeats, hfeats: list, fc1_layer, fc2_layer, outclass, gptype='max', ginfeat=None, num_query_vectors=1):
        super(GraphNN, self).__init__()
        self.mtype = mtype
        self.gptype = gptype
        self.hfeats = hfeats
        self.device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

        if mtype[0] == "GIN":          
          self.conv1 = get_convolution_layer(input_dimension=infeats, output_dimension=hfeats[0],
                                             name=mtype, agg_hidden_dimension=ginfeat)
          
          if len(hfeats) >= 2:
            self.conv2 = get_convolution_layer(input_dimension=hfeats[0], output_dimension=hfeats[1],
                                               name=mtype, agg_hidden_dimension=ginfeat)
          if len(hfeats) >= 3:
            self.conv3 = get_convolution_layer(input_dimension=hfeats[1], output_dimension=hfeats[2],
                                               name=mtype, agg_hidden_dimension=ginfeat)
        else:          
          if mtype != ["GAT"]:
            self.conv1 = get_convolution_layer(input_dimension=infeats, output_dimension=hfeats[0], name=mtype)
            if len(hfeats) >= 2:
                self.conv2 = get_convolution_layer(input_dimension=hfeats[0], output_dimension=hfeats[1], name=mtype)
            if len(hfeats) >= 3:
                self.conv3 = get_convolution_layer(input_dimension=hfeats[1], output_dimension=hfeats[2], name=mtype)
          else:
            if len(hfeats) > 1:
              self.conv1 = get_convolution_layer(input_dimension=infeats, output_dimension=hfeats[0], name=mtype, heads=8)
            elif len(hfeats) == 1:
              self.conv1 = get_convolution_layer(input_dimension=infeats, output_dimension=hfeats[0], name=mtype, heads=1)
            if len(hfeats) > 2:
              self.conv2 = get_convolution_layer(input_dimension=(hfeats[0] * 8), output_dimension=(hfeats[1] * 8), name=mtype, heads=8)
            elif len(hfeats) == 2:
              self.conv2 = get_convolution_layer(input_dimension=(hfeats[0] * 8), output_dimension=hfeats[1], name=mtype, heads=1)
              self.GPH = get_convolution_layer(input_dimension=hfeats[-1], output_dimension=hfeats[-1], name=mtype, heads=1)
            if len(hfeats) == 3:
              self.conv3 = get_convolution_layer(input_dimension=(hfeats[1] * 8), output_dimension=hfeats[2], name=mtype, heads=1)
        # In GraphNN's __init__
        if gptype == 'cross_attention':
            self.pooling = MultiHeadCrossAttentionPooling(hidden_dim=hfeats[-1], num_query_vectors=num_query_vectors)
            fc1_input_dim = hfeats[-1] * num_query_vectors
        else:
            self.pooling = get_pooling_method(gptype, hidden_dim=hfeats[-1])  # Pass the hidden dimension
            fc1_input_dim = hfeats[-1]

        # Adjust FC layers for concatenated output
        self.fc1 = nn.Linear(fc1_input_dim, fc1_layer)
        self.fc2 = nn.Linear(fc1_layer, fc2_layer)
        self.fc3 = nn.Linear(fc2_layer, outclass)

        nn.init.xavier_uniform_(self.fc1.weight)
        nn.init.xavier_uniform_(self.fc2.weight)
        nn.init.xavier_uniform_(self.fc3.weight)
    
    def create_graph_adjacency(self, num_nodes):
        src = []
        dest = []
        for i in range(num_nodes):
            for j in range(num_nodes):
                if i != j:
                    src.append(i)
                    dest.append(j)
        src = torch.tensor(src)
        dest = torch.tensor(dest)
        return dgl.graph((src, dest), num_nodes=num_nodes)

    def create_graph(self, features):
        g = self.create_graph_adjacency(features.shape[0])
        g = g.add_self_loop().to(self.device)
        g.ndata["features"] = features
        return g.add_self_loop().to(self.device)
        
    def forward(self, g, infeats):
        # Apply graph convolution and activation.
        h = self.conv1(g, infeats)
        if self.mtype == ["GAT"]: h = h.reshape(h.shape[0], -1)
        if len(self.hfeats) >= 2:
          h = self.conv2(g, h)
          if self.mtype == ["GAT"]: h = h.reshape(h.shape[0], -1)
        if len(self.hfeats) >= 3:
          h = self.conv3(g, h)
          if self.mtype == ["GAT"]: h = h.reshape(h.shape[0], -1)
        # with g.local_scope():

        g.ndata['features'] = h
        if self.gptype == "cross_attention":
            h = self.pooling(g, g.ndata['features'])
        elif self.gptype == "transformer":
            enc_nodes, dec_nodes = get_pooling_method(self.gptype)
            h = enc_nodes(g, g.ndata['features'])
            h = dec_nodes(g, g.ndata['features'])
        else:
            h = self.pooling(g, g.ndata['features'])
        
        g = self.create_graph(h.clone())
        h_gph = self.GPH(g, g.ndata['features'])
        h += h_gph.squeeze()
        ans = self.fc1(h)
        ans = F.relu(ans)
        ans = self.fc2(ans)
        ans = F.relu(ans)
        return self.fc3(ans)

    def save(self, path):
      torch.save(self.state_dict(), path)

    def load(self, path):
      self.load_state_dict(torch.load(path))

# Training

In [16]:
from dgl.data import DGLDataset
from dgl.dataloading import GraphDataLoader

class GraphDataset(DGLDataset):
    def __init__(self, graphs, labels):
        super().__init__(name='graph_dataset')
        self.graphs = graphs
        self.labels = labels
    def process(self):
        # Here, you could preprocess the data if needed.
        pass

    def __getitem__(self, idx):
        return self.graphs[idx], self.labels[idx]

    def __len__(self):
        return len(self.graphs)

In [17]:
def train_and_eval(dataloader, tdataloader, mtype, s_epoch, e_epoch, n_workers, n_feats, hfeats, gptype, ginfeat, num_query_vectors):
    model = GraphNN(mtype=mtype, infeats=n_feats, hfeats=hfeats, fc1_layer=256, fc2_layer=64, outclass=2, gptype=gptype, ginfeat=ginfeat)
    model.to(model.device)
    print(model)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.0005)
    criterion = torch.nn.CrossEntropyLoss()

    result = {
        "data": os.path.basename(data_path),
        "loss":[],
        "val_acc": [],
        "val_f1": [],
        "epoch": []
    }

    for epoch in (range(s_epoch, e_epoch)):
        bloss, bpred, blabel = [], [], []
        for batched_graph, label_batch in tqdm(dataloader):
            batched_graph, label_batch = batched_graph.to(model.device), label_batch.to(model.device)
            feats = batched_graph.ndata['features']
            model.train()
            pred_batch = model(batched_graph, feats)
            loss = criterion(pred_batch, label_batch)
            out_batch = pred_batch.argmax(dim=1).long()
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            bloss.append(loss.item())
            bpred.extend(out_batch.tolist())
            blabel.extend(label_batch.tolist())


        result['loss'].append(sum(bloss)/len(bloss))
        result['epoch'].append(epoch)
        print("Epoch:", epoch, "   Loss:", sum(bloss)/len(bloss),f"   Accuracy: {(accuracy_score(bpred, blabel)* 100):.4f}%")
        # if os.path.exists(f"/content/drive/MyDrive/ScamSolidityCodeDetection/ModelWeights/{mtype[0]}_{mtype[1]}_{len(hfeats)}_{gptype}_f{n_feats}") == False:
        #     os.mkdir(f"/content/drive/MyDrive/ScamSolidityCodeDetection/ModelWeights/{mtype[0]}_{mtype[1]}_{len(hfeats)}_{gptype}_f{n_feats}")
        # model.save(f"/content/drive/MyDrive/ScamSolidityCodeDetection/ModelWeights/{mtype[0]}_{mtype[1]}_{len(hfeats)}_{gptype}_f{n_feats}/model_{os.path.basename(data_path)}_{str(epoch).zfill(2)}.pt")
        model.eval()
        with torch.no_grad():
            tpred, tlabel = [], []
            for tbatched_graph, tlabels in (tdataloader):
                tbatched_graph, tlabels = tbatched_graph.to(model.device), tlabels.to(model.device)
                tfeats = tbatched_graph.ndata['features']
                out = model(tbatched_graph, tfeats)
                preds = out.argmax(dim=1).long()
                tpred.extend(preds.tolist())
                tlabel.extend(tlabels.tolist())

            print(f'Val Accuracy: {(accuracy_score(tlabel, tpred) * 100):.2f}%')
            print(f'Val F1 Score: {(f1_score(np.array(tlabel), np.array(tpred)) * 100):.2f}%')
            print(f'Val Precision: {(precision_score(tlabel, tpred) * 100):.2f}%')
            print(f'Val Recall: {(recall_score(tlabel, tpred) * 100):.2f}%')
            result['val_acc'].append(accuracy_score(tlabel, tpred))
            result['val_f1'].append(f1_score(np.array(tlabel), np.array(tpred)))

    plot(result["epoch"], result["loss"])
    return result

In [18]:
import random

random.seed(42)

data_path = "/kaggle/input/sol2graphconverter/SmartContractVulnerabilityDetection/SourceCodeSyntaxDataset/ReentrancyDataset"

train_df = readData(f"{data_path}/Train", 2047, 2047)
train_df = train_df.sample(frac=1).reset_index(drop=True)

test_df = readData(f"{data_path}/Test", 2047, 2047)
test_df = test_df.sample(frac=1).reset_index(drop=True)

display(train_df.head())
display(test_df.head())

print(f"Train Dataset size: {len(train_df)} files")
print(f"Test Dataset size: {len(test_df)} files")

X_train, y_train = train_df.drop(['label'], axis=1), train_df['label']
X_test, y_test = test_df.drop(['label'], axis=1), test_df['label']
# X_train, X_test, y_train, y_test = train_test_split(df.drop(['label'], axis=1), df['label'], test_size=0.2, random_state=42)

graphs = createBatchMulThread_MultiOp(X_train['filename'].tolist(), 16, 773)
graphs = [dgl.add_self_loop(g) for g in graphs]
dataset = GraphDataset(graphs, Tensor(list(y_train)).long())
dataloader = GraphDataLoader(
    dataset,
    batch_size=128,
    drop_last=False,
    shuffle=True)

tgraphs = createBatchMulThread_MultiOp(X_test['filename'].tolist(), 16, 773)
tgraphs = [dgl.add_self_loop(g) for g in tgraphs]
tdataset = GraphDataset(tgraphs, Tensor(list(y_test)).long())
tdataloader = GraphDataLoader(
    tdataset,
    batch_size=512,
    drop_last=False,
    shuffle=True)

                                            filename  label
0  /kaggle/input/sol2graphconverter/SmartContract...      0
1  /kaggle/input/sol2graphconverter/SmartContract...      1
2  /kaggle/input/sol2graphconverter/SmartContract...      1
3  /kaggle/input/sol2graphconverter/SmartContract...      1
4  /kaggle/input/sol2graphconverter/SmartContract...      0

                                            filename  label
0  /kaggle/input/sol2graphconverter/SmartContract...      0
1  /kaggle/input/sol2graphconverter/SmartContract...      0
2  /kaggle/input/sol2graphconverter/SmartContract...      1
3  /kaggle/input/sol2graphconverter/SmartContract...      0
4  /kaggle/input/sol2graphconverter/SmartContract...      1

Train Dataset size: 516 files
Test Dataset size: 135 files

In [20]:
# print(len(os.listdir("/kaggle/input/sc-vuldetection-dataset/SmartContractVulnerabilityDetection/SourceCodeSyntaxDataset/ReentrancyDataset/Test/NonVulnerable")))
# print(len(os.listdir("/kaggle/input/sc-vuldetection-dataset/SmartContractVulnerabilityDetection/SourceCodeSyntaxDataset/ReentrancyDataset/Test/Vulnerable")))

In [21]:
# print(len(os.listdir("/kaggle/input/sc-vuldetection-dataset/SmartContractVulnerabilityDetection/SourceCodeSyntaxDataset/ReentrancyDataset/Train/NonVulnerable")))
# print(len(os.listdir("/kaggle/input/sc-vuldetection-dataset/SmartContractVulnerabilityDetection/SourceCodeSyntaxDataset/ReentrancyDataset/Train/Vulnerable")))

In [22]:
print(len(train_df[train_df['label'] == 0]), len(train_df[train_df['label'] == 1]))
print(len(test_df[test_df['label'] == 0]), len(test_df[test_df['label'] == 1]))

250 266
68 67

In [ ]:
# GCN, SAGE, GAT, TAG, GIN
# layer 1, 2, 3
# 128
# 256, 128
# 256, 256, 128

n_feats = 773
n_batch=128

# result_dict = {}
# for mtype in [['GAT'], ['SAGE', 'pool'], ['SAGE', 'mean'], ['SAGE', 'lstm'], ['GCN'], ['TAG'], ['GIN', 'max'], ['GIN', 'sum'], ['GIN', 'mean']]:
#     for hfeats in [[128], [256, 128], [256, 256, 128]]:
#         for gptype in ['sum', 'mean', 'max']:
#             print(mtype, hfeats, gptype)
#             tmp = train_and_eval(dataloader=dataloader, tdataloader=tdataloader, mtype=mtype,
#                                         s_epoch=0, e_epoch=500, n_workers=64, n_feats=n_feats,
#                                         hfeats=hfeats, gptype=gptype, ginfeat=1024)
#             res = [(i, j) for i, j in zip(tmp['val_f1'], tmp['val_acc'])]
#             print(max(res))
#             result_dict[f"{mtype}_{hfeats}_{gptype}"] = tmp

result = train_and_eval(dataloader=dataloader, tdataloader=tdataloader, mtype=['GAT'],
                                        s_epoch=0, e_epoch=200, n_workers=64, n_feats=n_feats,
                                        hfeats=[1024, 512], gptype='cross_attention', ginfeat=1024, num_query_vectors=2)

GraphNN(
  (conv1): GATConv(
    (fc): Linear(in_features=773, out_features=8192, bias=False)
    (feat_drop): Dropout(p=0.0, inplace=False)
    (attn_drop): Dropout(p=0.0, inplace=False)
    (leaky_relu): LeakyReLU(negative_slope=0.2)
  )
  (conv2): GATConv(
    (fc): Linear(in_features=8192, out_features=512, bias=False)
    (feat_drop): Dropout(p=0.0, inplace=False)
    (attn_drop): Dropout(p=0.0, inplace=False)
    (leaky_relu): LeakyReLU(negative_slope=0.2)
  )
  (GPH): GATConv(
    (fc): Linear(in_features=512, out_features=512, bias=False)
    (feat_drop): Dropout(p=0.0, inplace=False)
    (attn_drop): Dropout(p=0.0, inplace=False)
    (leaky_relu): LeakyReLU(negative_slope=0.2)
  )
  (pooling): MultiHeadCrossAttentionPooling(
    (key_transform): Linear(in_features=512, out_features=512, bias=True)
    (value_transform): Linear(in_features=512, out_features=512, bias=True)
    (output_projection): Linear(in_features=512, out_features=512, bias=True)
  )
  (fc1): Linear(in_features=512, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=2, bias=True)
)

100%|██████████| 5/5 [00:01<00:00,  5.00it/s]

Epoch: 0    Loss: 0.8945682525634766    Accuracy: 52.1318%
Val Accuracy: 49.63%
Val F1 Score: 66.34%
Val Precision: 49.63%
Val Recall: 100.00%

100%|██████████| 5/5 [00:00<00:00,  5.37it/s]

Epoch: 1    Loss: 0.8699935555458069    Accuracy: 56.5891%
Val Accuracy: 63.70%
Val F1 Score: 47.31%
Val Precision: 84.62%
Val Recall: 32.84%

100%|██████████| 5/5 [00:00<00:00,  5.38it/s]

Epoch: 2    Loss: 0.6847295165061951    Accuracy: 61.2403%
Val Accuracy: 52.59%
Val F1 Score: 67.01%
Val Precision: 51.18%
Val Recall: 97.01%

100%|██████████| 5/5 [00:00<00:00,  5.42it/s]

Epoch: 3    Loss: 0.6325924396514893    Accuracy: 64.5349%
Val Accuracy: 59.26%
Val F1 Score: 62.07%
Val Precision: 57.69%
Val Recall: 67.16%

100%|██████████| 5/5 [00:00<00:00,  5.51it/s]

Epoch: 4    Loss: 0.5745700478553772    Accuracy: 70.3488%
Val Accuracy: 63.70%
Val F1 Score: 51.49%
Val Precision: 76.47%
Val Recall: 38.81%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 5    Loss: 0.5813595414161682    Accuracy: 68.7984%
Val Accuracy: 65.93%
Val F1 Score: 53.06%
Val Precision: 83.87%
Val Recall: 38.81%

100%|██████████| 5/5 [00:00<00:00,  5.50it/s]

Epoch: 6    Loss: 0.6055258512496948    Accuracy: 69.3798%
Val Accuracy: 63.70%
Val F1 Score: 47.31%
Val Precision: 84.62%
Val Recall: 32.84%

100%|██████████| 5/5 [00:00<00:00,  5.47it/s]

Epoch: 7    Loss: 0.6382402420043946    Accuracy: 66.0853%
Val Accuracy: 54.81%
Val F1 Score: 67.03%
Val Precision: 52.54%
Val Recall: 92.54%

100%|██████████| 5/5 [00:00<00:00,  5.21it/s]

Epoch: 8    Loss: 0.6123328685760498    Accuracy: 68.2171%
Val Accuracy: 62.96%
Val F1 Score: 62.12%
Val Precision: 63.08%
Val Recall: 61.19%

100%|██████████| 5/5 [00:00<00:00,  5.48it/s]

Epoch: 9    Loss: 0.5725591778755188    Accuracy: 73.2558%
Val Accuracy: 62.96%
Val F1 Score: 60.94%
Val Precision: 63.93%
Val Recall: 58.21%

100%|██████████| 5/5 [00:00<00:00,  5.37it/s]

Epoch: 10    Loss: 0.5133320450782776    Accuracy: 72.4806%
Val Accuracy: 66.67%
Val F1 Score: 57.14%
Val Precision: 78.95%
Val Recall: 44.78%

100%|██████████| 5/5 [00:00<00:00,  5.47it/s]

Epoch: 11    Loss: 0.5771130919456482    Accuracy: 72.6744%
Val Accuracy: 51.11%
Val F1 Score: 66.67%
Val Precision: 50.38%
Val Recall: 98.51%

100%|██████████| 5/5 [00:00<00:00,  5.46it/s]

Epoch: 12    Loss: 0.7287649869918823    Accuracy: 64.7287%
Val Accuracy: 67.41%
Val F1 Score: 60.00%
Val Precision: 76.74%
Val Recall: 49.25%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 13    Loss: 0.6348843932151794    Accuracy: 71.5116%
Val Accuracy: 53.33%
Val F1 Score: 67.36%
Val Precision: 51.59%
Val Recall: 97.01%

100%|██████████| 5/5 [00:00<00:00,  5.39it/s]

Epoch: 14    Loss: 0.7798696041107178    Accuracy: 63.5659%
Val Accuracy: 64.44%
Val F1 Score: 47.83%
Val Precision: 88.00%
Val Recall: 32.84%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 15    Loss: 0.5986631751060486    Accuracy: 69.3798%
Val Accuracy: 51.85%
Val F1 Score: 63.28%
Val Precision: 50.91%
Val Recall: 83.58%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 16    Loss: 0.6417925119400024    Accuracy: 72.8682%
Val Accuracy: 65.19%
Val F1 Score: 54.37%
Val Precision: 77.78%
Val Recall: 41.79%

100%|██████████| 5/5 [00:00<00:00,  5.29it/s]

Epoch: 17    Loss: 0.6150107502937316    Accuracy: 71.5116%
Val Accuracy: 60.74%
Val F1 Score: 60.74%
Val Precision: 60.29%
Val Recall: 61.19%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 18    Loss: 0.5217945516109467    Accuracy: 71.1240%
Val Accuracy: 60.00%
Val F1 Score: 51.79%
Val Precision: 64.44%
Val Recall: 43.28%

100%|██████████| 5/5 [00:00<00:00,  5.35it/s]

Epoch: 19    Loss: 0.622975480556488    Accuracy: 69.7674%
Val Accuracy: 60.00%
Val F1 Score: 58.46%
Val Precision: 60.32%
Val Recall: 56.72%

100%|██████████| 5/5 [00:00<00:00,  5.01it/s]

Epoch: 20    Loss: 0.5823807835578918    Accuracy: 73.4496%
Val Accuracy: 56.30%
Val F1 Score: 64.24%
Val Precision: 54.08%
Val Recall: 79.10%

100%|██████████| 5/5 [00:00<00:00,  5.22it/s]

Epoch: 21    Loss: 0.6050500512123108    Accuracy: 72.6744%
Val Accuracy: 68.89%
Val F1 Score: 60.38%
Val Precision: 82.05%
Val Recall: 47.76%

100%|██████████| 5/5 [00:00<00:00,  5.29it/s]

Epoch: 22    Loss: 0.5769959568977356    Accuracy: 73.4496%
Val Accuracy: 68.89%
Val F1 Score: 61.11%
Val Precision: 80.49%
Val Recall: 49.25%

100%|██████████| 5/5 [00:00<00:00,  5.19it/s]

Epoch: 23    Loss: 0.5053680598735809    Accuracy: 70.1550%
Val Accuracy: 54.81%
Val F1 Score: 67.03%
Val Precision: 52.54%
Val Recall: 92.54%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 24    Loss: 0.6581058382987977    Accuracy: 72.6744%
Val Accuracy: 59.26%
Val F1 Score: 64.52%
Val Precision: 56.82%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.43it/s]

Epoch: 25    Loss: 0.5761803209781646    Accuracy: 65.5039%
Val Accuracy: 54.81%
Val F1 Score: 65.54%
Val Precision: 52.73%
Val Recall: 86.57%

100%|██████████| 5/5 [00:00<00:00,  5.46it/s]

Epoch: 26    Loss: 0.6530699372291565    Accuracy: 72.8682%
Val Accuracy: 62.22%
Val F1 Score: 61.65%
Val Precision: 62.12%
Val Recall: 61.19%

100%|██████████| 5/5 [00:00<00:00,  5.39it/s]

Epoch: 27    Loss: 0.6746085345745086    Accuracy: 75.5814%
Val Accuracy: 62.22%
Val F1 Score: 69.46%
Val Precision: 58.00%
Val Recall: 86.57%

100%|██████████| 5/5 [00:00<00:00,  5.39it/s]

Epoch: 28    Loss: 0.5352212727069855    Accuracy: 74.2248%
Val Accuracy: 52.59%
Val F1 Score: 66.67%
Val Precision: 51.20%
Val Recall: 95.52%

100%|██████████| 5/5 [00:00<00:00,  5.36it/s]

Epoch: 29    Loss: 0.5682252407073974    Accuracy: 69.7674%
Val Accuracy: 70.37%
Val F1 Score: 62.26%
Val Precision: 84.62%
Val Recall: 49.25%

100%|██████████| 5/5 [00:00<00:00,  5.37it/s]

Epoch: 30    Loss: 0.7129243731498718    Accuracy: 75.0000%
Val Accuracy: 66.67%
Val F1 Score: 70.97%
Val Precision: 62.50%
Val Recall: 82.09%

100%|██████████| 5/5 [00:00<00:00,  5.39it/s]

Epoch: 31    Loss: 0.5907364845275879    Accuracy: 77.9070%
Val Accuracy: 69.63%
Val F1 Score: 69.17%
Val Precision: 69.70%
Val Recall: 68.66%

100%|██████████| 5/5 [00:00<00:00,  5.31it/s]

Epoch: 32    Loss: 0.5294724345207215    Accuracy: 73.6434%
Val Accuracy: 62.96%
Val F1 Score: 70.59%
Val Precision: 58.25%
Val Recall: 89.55%

100%|██████████| 5/5 [00:00<00:00,  5.36it/s]

Epoch: 33    Loss: 0.5969040393829346    Accuracy: 74.8062%
Val Accuracy: 58.52%
Val F1 Score: 69.23%
Val Precision: 54.78%
Val Recall: 94.03%

100%|██████████| 5/5 [00:00<00:00,  5.38it/s]

Epoch: 34    Loss: 0.5397183954715729    Accuracy: 74.4186%
Val Accuracy: 68.15%
Val F1 Score: 55.67%
Val Precision: 90.00%
Val Recall: 40.30%

100%|██████████| 5/5 [00:00<00:00,  5.39it/s]

Epoch: 35    Loss: 0.5468748331069946    Accuracy: 75.0000%
Val Accuracy: 62.96%
Val F1 Score: 70.93%
Val Precision: 58.10%
Val Recall: 91.04%

100%|██████████| 5/5 [00:00<00:00,  5.19it/s]

Epoch: 36    Loss: 0.6082351863384247    Accuracy: 75.1938%
Val Accuracy: 66.67%
Val F1 Score: 70.59%
Val Precision: 62.79%
Val Recall: 80.60%

100%|██████████| 5/5 [00:00<00:00,  5.32it/s]

Epoch: 37    Loss: 0.5932903051376343    Accuracy: 69.1860%
Val Accuracy: 62.96%
Val F1 Score: 70.93%
Val Precision: 58.10%
Val Recall: 91.04%

100%|██████████| 5/5 [00:00<00:00,  5.29it/s]

Epoch: 38    Loss: 0.5286851942539215    Accuracy: 75.5814%
Val Accuracy: 72.59%
Val F1 Score: 67.83%
Val Precision: 81.25%
Val Recall: 58.21%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 39    Loss: 0.6477514743804932    Accuracy: 77.5194%
Val Accuracy: 62.96%
Val F1 Score: 67.53%
Val Precision: 59.77%
Val Recall: 77.61%

100%|██████████| 5/5 [00:00<00:00,  5.40it/s]

Epoch: 40    Loss: 0.5243847727775574    Accuracy: 77.7132%
Val Accuracy: 69.63%
Val F1 Score: 62.39%
Val Precision: 80.95%
Val Recall: 50.75%

100%|██████████| 5/5 [00:00<00:00,  5.39it/s]

Epoch: 41    Loss: 0.5047022342681885    Accuracy: 76.5504%
Val Accuracy: 53.33%
Val F1 Score: 62.72%
Val Precision: 51.96%
Val Recall: 79.10%

100%|██████████| 5/5 [00:00<00:00,  5.32it/s]

Epoch: 42    Loss: 0.5368099808692932    Accuracy: 73.4496%
Val Accuracy: 62.96%
Val F1 Score: 44.44%
Val Precision: 86.96%
Val Recall: 29.85%

100%|██████████| 5/5 [00:00<00:00,  5.29it/s]

Epoch: 43    Loss: 0.6728338837623596    Accuracy: 66.2791%
Val Accuracy: 54.07%
Val F1 Score: 60.76%
Val Precision: 52.75%
Val Recall: 71.64%

100%|██████████| 5/5 [00:00<00:00,  5.35it/s]

Epoch: 44    Loss: 0.5856834053993225    Accuracy: 70.7364%
Val Accuracy: 53.33%
Val F1 Score: 63.58%
Val Precision: 51.89%
Val Recall: 82.09%

100%|██████████| 5/5 [00:00<00:00,  5.35it/s]

Epoch: 45    Loss: 0.5166819453239441    Accuracy: 72.2868%
Val Accuracy: 61.48%
Val F1 Score: 58.06%
Val Precision: 63.16%
Val Recall: 53.73%

100%|██████████| 5/5 [00:00<00:00,  5.26it/s]

Epoch: 46    Loss: 0.5104215264320373    Accuracy: 74.4186%
Val Accuracy: 72.59%
Val F1 Score: 66.06%
Val Precision: 85.71%
Val Recall: 53.73%

100%|██████████| 5/5 [00:00<00:00,  5.35it/s]

Epoch: 47    Loss: 0.4830382466316223    Accuracy: 76.9380%
Val Accuracy: 57.78%
Val F1 Score: 64.15%
Val Precision: 55.43%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.20it/s]

Epoch: 48    Loss: 0.4657609581947327    Accuracy: 75.9690%
Val Accuracy: 69.63%
Val F1 Score: 60.95%
Val Precision: 84.21%
Val Recall: 47.76%

100%|██████████| 5/5 [00:00<00:00,  5.20it/s]

Epoch: 49    Loss: 0.47688993215560915    Accuracy: 76.7442%
Val Accuracy: 59.26%
Val F1 Score: 69.27%
Val Precision: 55.36%
Val Recall: 92.54%

100%|██████████| 5/5 [00:00<00:00,  5.23it/s]

Epoch: 50    Loss: 0.5575729668140411    Accuracy: 73.2558%
Val Accuracy: 61.48%
Val F1 Score: 69.77%
Val Precision: 57.14%
Val Recall: 89.55%

100%|██████████| 5/5 [00:00<00:00,  5.36it/s]

Epoch: 51    Loss: 0.4577777564525604    Accuracy: 74.4186%
Val Accuracy: 66.67%
Val F1 Score: 69.80%
Val Precision: 63.41%
Val Recall: 77.61%

100%|██████████| 5/5 [00:00<00:00,  5.42it/s]

Epoch: 52    Loss: 0.4257103979587555    Accuracy: 80.0388%
Val Accuracy: 74.81%
Val F1 Score: 72.58%
Val Precision: 78.95%
Val Recall: 67.16%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 53    Loss: 0.41407519578933716    Accuracy: 79.4574%
Val Accuracy: 62.96%
Val F1 Score: 69.51%
Val Precision: 58.76%
Val Recall: 85.07%

100%|██████████| 5/5 [00:00<00:00,  5.33it/s]

Epoch: 54    Loss: 0.44061199426651    Accuracy: 79.0698%
Val Accuracy: 73.33%
Val F1 Score: 66.04%
Val Precision: 89.74%
Val Recall: 52.24%

100%|██████████| 5/5 [00:00<00:00,  5.35it/s]

Epoch: 55    Loss: 0.4347061812877655    Accuracy: 78.4884%
Val Accuracy: 58.52%
Val F1 Score: 67.06%
Val Precision: 55.34%
Val Recall: 85.07%

100%|██████████| 5/5 [00:00<00:00,  5.27it/s]

Epoch: 56    Loss: 0.46702266335487364    Accuracy: 81.3953%
Val Accuracy: 69.63%
Val F1 Score: 71.72%
Val Precision: 66.67%
Val Recall: 77.61%

100%|██████████| 5/5 [00:00<00:00,  5.33it/s]

Epoch: 57    Loss: 0.4161172151565552    Accuracy: 81.2016%
Val Accuracy: 75.56%
Val F1 Score: 75.19%
Val Precision: 75.76%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 58    Loss: 0.4215458810329437    Accuracy: 80.6202%
Val Accuracy: 61.48%
Val F1 Score: 70.11%
Val Precision: 57.01%
Val Recall: 91.04%

100%|██████████| 5/5 [00:00<00:00,  5.52it/s]

Epoch: 59    Loss: 0.4926148056983948    Accuracy: 79.8450%
Val Accuracy: 77.04%
Val F1 Score: 73.04%
Val Precision: 87.50%
Val Recall: 62.69%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 60    Loss: 0.4588248014450073    Accuracy: 80.4264%
Val Accuracy: 51.11%
Val F1 Score: 66.33%
Val Precision: 50.39%
Val Recall: 97.01%

100%|██████████| 5/5 [00:00<00:00,  5.40it/s]

Epoch: 61    Loss: 0.5446576297283172    Accuracy: 68.2171%
Val Accuracy: 75.56%
Val F1 Score: 71.79%
Val Precision: 84.00%
Val Recall: 62.69%

100%|██████████| 5/5 [00:00<00:00,  5.46it/s]

Epoch: 62    Loss: 0.5138013124465942    Accuracy: 69.9612%
Val Accuracy: 70.37%
Val F1 Score: 73.33%
Val Precision: 66.27%
Val Recall: 82.09%

100%|██████████| 5/5 [00:00<00:00,  5.42it/s]

Epoch: 63    Loss: 0.5340195178985596    Accuracy: 76.7442%
Val Accuracy: 51.85%
Val F1 Score: 66.67%
Val Precision: 50.78%
Val Recall: 97.01%

100%|██████████| 5/5 [00:00<00:00,  5.32it/s]

Epoch: 64    Loss: 0.564727520942688    Accuracy: 71.5116%
Val Accuracy: 71.11%
Val F1 Score: 62.14%
Val Precision: 88.89%
Val Recall: 47.76%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 65    Loss: 0.5435811042785644    Accuracy: 72.2868%
Val Accuracy: 57.78%
Val F1 Score: 67.05%
Val Precision: 54.72%
Val Recall: 86.57%

100%|██████████| 5/5 [00:00<00:00,  5.36it/s]

Epoch: 66    Loss: 0.5021555721759796    Accuracy: 73.4496%
Val Accuracy: 57.04%
Val F1 Score: 64.20%
Val Precision: 54.74%
Val Recall: 77.61%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 67    Loss: 0.4634450376033783    Accuracy: 79.2636%
Val Accuracy: 75.56%
Val F1 Score: 70.80%
Val Precision: 86.96%
Val Recall: 59.70%

100%|██████████| 5/5 [00:00<00:00,  5.50it/s]

Epoch: 68    Loss: 0.4504413306713104    Accuracy: 80.6202%
Val Accuracy: 58.52%
Val F1 Score: 68.54%
Val Precision: 54.95%
Val Recall: 91.04%

100%|██████████| 5/5 [00:00<00:00,  5.51it/s]

Epoch: 69    Loss: 0.5579623281955719    Accuracy: 67.2481%
Val Accuracy: 58.52%
Val F1 Score: 68.89%
Val Precision: 54.87%
Val Recall: 92.54%

100%|██████████| 5/5 [00:00<00:00,  5.43it/s]

Epoch: 70    Loss: 0.4520146131515503    Accuracy: 80.4264%
Val Accuracy: 72.59%
Val F1 Score: 68.91%
Val Precision: 78.85%
Val Recall: 61.19%

100%|██████████| 5/5 [00:00<00:00,  5.40it/s]

Epoch: 71    Loss: 0.40221506357192993    Accuracy: 79.8450%
Val Accuracy: 59.26%
Val F1 Score: 68.93%
Val Precision: 55.45%
Val Recall: 91.04%

100%|██████████| 5/5 [00:00<00:00,  5.47it/s]

Epoch: 72    Loss: 0.44645283222198484    Accuracy: 78.4884%
Val Accuracy: 77.04%
Val F1 Score: 73.50%
Val Precision: 86.00%
Val Recall: 64.18%

100%|██████████| 5/5 [00:00<00:00,  5.32it/s]

Epoch: 73    Loss: 0.3786705285310745    Accuracy: 81.5891%
Val Accuracy: 63.70%
Val F1 Score: 65.25%
Val Precision: 62.16%
Val Recall: 68.66%

100%|██████████| 5/5 [00:00<00:00,  5.46it/s]

Epoch: 74    Loss: 0.4137470662593842    Accuracy: 82.3643%
Val Accuracy: 71.11%
Val F1 Score: 70.68%
Val Precision: 71.21%
Val Recall: 70.15%

100%|██████████| 5/5 [00:00<00:00,  5.38it/s]

Epoch: 75    Loss: 0.4580682754516602    Accuracy: 82.5581%
Val Accuracy: 62.96%
Val F1 Score: 66.67%
Val Precision: 60.24%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 76    Loss: 0.36164721846580505    Accuracy: 83.5271%
Val Accuracy: 59.26%
Val F1 Score: 64.52%
Val Precision: 56.82%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.46it/s]

Epoch: 77    Loss: 0.3623088479042053    Accuracy: 83.1395%
Val Accuracy: 62.22%
Val F1 Score: 64.83%
Val Precision: 60.26%
Val Recall: 70.15%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 78    Loss: 0.3580158710479736    Accuracy: 83.1395%
Val Accuracy: 58.52%
Val F1 Score: 68.89%
Val Precision: 54.87%
Val Recall: 92.54%

100%|██████████| 5/5 [00:00<00:00,  5.05it/s]

Epoch: 79    Loss: 0.5710204303264618    Accuracy: 80.0388%
Val Accuracy: 60.74%
Val F1 Score: 67.08%
Val Precision: 57.45%
Val Recall: 80.60%

100%|██████████| 5/5 [00:00<00:00,  5.17it/s]

Epoch: 80    Loss: 0.45834255814552305    Accuracy: 75.1938%
Val Accuracy: 57.78%
Val F1 Score: 67.43%
Val Precision: 54.63%
Val Recall: 88.06%

100%|██████████| 5/5 [00:00<00:00,  5.35it/s]

Epoch: 81    Loss: 0.4465449810028076    Accuracy: 82.9457%
Val Accuracy: 73.33%
Val F1 Score: 70.49%
Val Precision: 78.18%
Val Recall: 64.18%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 82    Loss: 0.4831128716468811    Accuracy: 79.2636%
Val Accuracy: 60.00%
Val F1 Score: 64.47%
Val Precision: 57.65%
Val Recall: 73.13%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 83    Loss: 0.3670586943626404    Accuracy: 83.7209%
Val Accuracy: 59.26%
Val F1 Score: 64.97%
Val Precision: 56.67%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 84    Loss: 0.4401764750480652    Accuracy: 84.3023%
Val Accuracy: 76.30%
Val F1 Score: 71.43%
Val Precision: 88.89%
Val Recall: 59.70%

100%|██████████| 5/5 [00:00<00:00,  5.47it/s]

Epoch: 85    Loss: 0.42436124086380006    Accuracy: 79.4574%
Val Accuracy: 57.78%
Val F1 Score: 65.87%
Val Precision: 55.00%
Val Recall: 82.09%

100%|██████████| 5/5 [00:00<00:00,  5.47it/s]

Epoch: 86    Loss: 0.5642974734306335    Accuracy: 79.2636%
Val Accuracy: 77.78%
Val F1 Score: 75.00%
Val Precision: 84.91%
Val Recall: 67.16%

100%|██████████| 5/5 [00:00<00:00,  5.52it/s]

Epoch: 87    Loss: 0.4424277186393738    Accuracy: 77.7132%
Val Accuracy: 71.85%
Val F1 Score: 64.15%
Val Precision: 87.18%
Val Recall: 50.75%

100%|██████████| 5/5 [00:00<00:00,  5.47it/s]

Epoch: 88    Loss: 0.4981670081615448    Accuracy: 81.3953%
Val Accuracy: 57.04%
Val F1 Score: 63.29%
Val Precision: 54.95%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 89    Loss: 0.3542597025632858    Accuracy: 83.3333%
Val Accuracy: 74.07%
Val F1 Score: 71.54%
Val Precision: 78.57%
Val Recall: 65.67%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 90    Loss: 0.366793492436409    Accuracy: 82.9457%
Val Accuracy: 69.63%
Val F1 Score: 69.17%
Val Precision: 69.70%
Val Recall: 68.66%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 91    Loss: 0.4612278282642365    Accuracy: 80.2326%
Val Accuracy: 75.56%
Val F1 Score: 74.02%
Val Precision: 78.33%
Val Recall: 70.15%

100%|██████████| 5/5 [00:00<00:00,  5.30it/s]

Epoch: 92    Loss: 0.4682416975498199    Accuracy: 81.7829%
Val Accuracy: 68.15%
Val F1 Score: 71.14%
Val Precision: 64.63%
Val Recall: 79.10%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 93    Loss: 0.40043683648109435    Accuracy: 82.1705%
Val Accuracy: 58.52%
Val F1 Score: 66.67%
Val Precision: 55.45%
Val Recall: 83.58%

100%|██████████| 5/5 [00:00<00:00,  5.42it/s]

Epoch: 94    Loss: 0.3750267669558525    Accuracy: 81.9767%
Val Accuracy: 74.07%
Val F1 Score: 73.28%
Val Precision: 75.00%
Val Recall: 71.64%

100%|██████████| 5/5 [00:00<00:00,  5.48it/s]

Epoch: 95    Loss: 0.42453712224960327    Accuracy: 82.3643%
Val Accuracy: 57.04%
Val F1 Score: 68.13%
Val Precision: 53.91%
Val Recall: 92.54%

100%|██████████| 5/5 [00:00<00:00,  5.52it/s]

Epoch: 96    Loss: 0.4928383469581604    Accuracy: 77.3256%
Val Accuracy: 76.30%
Val F1 Score: 73.77%
Val Precision: 81.82%
Val Recall: 67.16%

100%|██████████| 5/5 [00:00<00:00,  5.58it/s]

Epoch: 97    Loss: 0.3722903490066528    Accuracy: 83.7209%
Val Accuracy: 60.00%
Val F1 Score: 69.66%
Val Precision: 55.86%
Val Recall: 92.54%

100%|██████████| 5/5 [00:00<00:00,  5.47it/s]

Epoch: 98    Loss: 0.39732698500156405    Accuracy: 80.4264%
Val Accuracy: 71.85%
Val F1 Score: 62.75%
Val Precision: 91.43%
Val Recall: 47.76%

100%|██████████| 5/5 [00:00<00:00,  5.24it/s]

Epoch: 99    Loss: 0.4916751146316528    Accuracy: 79.2636%
Val Accuracy: 53.33%
Val F1 Score: 66.67%
Val Precision: 51.64%
Val Recall: 94.03%

100%|██████████| 5/5 [00:00<00:00,  5.47it/s]

Epoch: 100    Loss: 0.4229421019554138    Accuracy: 75.0000%
Val Accuracy: 69.63%
Val F1 Score: 71.33%
Val Precision: 67.11%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.46it/s]

Epoch: 101    Loss: 0.4511528968811035    Accuracy: 81.9767%
Val Accuracy: 59.26%
Val F1 Score: 67.46%
Val Precision: 55.88%
Val Recall: 85.07%

100%|██████████| 5/5 [00:00<00:00,  5.43it/s]

Epoch: 102    Loss: 0.44577701985836027    Accuracy: 76.5504%
Val Accuracy: 60.00%
Val F1 Score: 68.60%
Val Precision: 56.19%
Val Recall: 88.06%

100%|██████████| 5/5 [00:00<00:00,  5.42it/s]

Epoch: 103    Loss: 0.5156784653663635    Accuracy: 82.5581%
Val Accuracy: 74.81%
Val F1 Score: 73.44%
Val Precision: 77.05%
Val Recall: 70.15%

100%|██████████| 5/5 [00:00<00:00,  5.38it/s]

Epoch: 104    Loss: 0.38464234471321107    Accuracy: 83.5271%
Val Accuracy: 58.52%
Val F1 Score: 68.54%
Val Precision: 54.95%
Val Recall: 91.04%

100%|██████████| 5/5 [00:00<00:00,  5.38it/s]

Epoch: 105    Loss: 0.465910005569458    Accuracy: 83.3333%
Val Accuracy: 71.85%
Val F1 Score: 72.46%
Val Precision: 70.42%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.47it/s]

Epoch: 106    Loss: 0.43043036460876466    Accuracy: 83.5271%
Val Accuracy: 62.22%
Val F1 Score: 67.52%
Val Precision: 58.89%
Val Recall: 79.10%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 107    Loss: 0.33518210649490354    Accuracy: 84.6899%
Val Accuracy: 71.11%
Val F1 Score: 72.73%
Val Precision: 68.42%
Val Recall: 77.61%

100%|██████████| 5/5 [00:00<00:00,  5.43it/s]

Epoch: 108    Loss: 0.54060138463974    Accuracy: 83.3333%
Val Accuracy: 66.67%
Val F1 Score: 69.80%
Val Precision: 63.41%
Val Recall: 77.61%

100%|██████████| 5/5 [00:00<00:00,  5.08it/s]

Epoch: 109    Loss: 0.34928702712059023    Accuracy: 85.2713%
Val Accuracy: 62.96%
Val F1 Score: 67.11%
Val Precision: 60.00%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.34it/s]

Epoch: 110    Loss: 0.4825860559940338    Accuracy: 83.5271%
Val Accuracy: 64.44%
Val F1 Score: 68.00%
Val Precision: 61.45%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.25it/s]

Epoch: 111    Loss: 0.3516699016094208    Accuracy: 84.8837%
Val Accuracy: 59.26%
Val F1 Score: 69.27%
Val Precision: 55.36%
Val Recall: 92.54%

100%|██████████| 5/5 [00:00<00:00,  5.31it/s]

Epoch: 112    Loss: 0.40667996257543565    Accuracy: 73.4496%
Val Accuracy: 62.22%
Val F1 Score: 68.71%
Val Precision: 58.33%
Val Recall: 83.58%

100%|██████████| 5/5 [00:00<00:00,  5.37it/s]

Epoch: 113    Loss: 0.3690475791692734    Accuracy: 82.3643%
Val Accuracy: 79.26%
Val F1 Score: 78.13%
Val Precision: 81.97%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 114    Loss: 0.38541982173919676    Accuracy: 82.5581%
Val Accuracy: 57.78%
Val F1 Score: 68.85%
Val Precision: 54.31%
Val Recall: 94.03%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 115    Loss: 0.5294020891189575    Accuracy: 72.4806%
Val Accuracy: 60.00%
Val F1 Score: 69.66%
Val Precision: 55.86%
Val Recall: 92.54%

100%|██████████| 5/5 [00:00<00:00,  5.43it/s]

Epoch: 116    Loss: 0.4241829514503479    Accuracy: 82.5581%
Val Accuracy: 75.56%
Val F1 Score: 72.27%
Val Precision: 82.69%
Val Recall: 64.18%

100%|██████████| 5/5 [00:00<00:00,  5.37it/s]

Epoch: 117    Loss: 0.4097976267337799    Accuracy: 80.8140%
Val Accuracy: 62.96%
Val F1 Score: 69.88%
Val Precision: 58.59%
Val Recall: 86.57%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 118    Loss: 0.41153703033924105    Accuracy: 78.6822%
Val Accuracy: 59.26%
Val F1 Score: 68.21%
Val Precision: 55.66%
Val Recall: 88.06%

100%|██████████| 5/5 [00:00<00:00,  5.46it/s]

Epoch: 119    Loss: 0.3680560886859894    Accuracy: 82.5581%
Val Accuracy: 78.52%
Val F1 Score: 75.63%
Val Precision: 86.54%
Val Recall: 67.16%

100%|██████████| 5/5 [00:00<00:00,  5.36it/s]

Epoch: 120    Loss: 0.384712415933609    Accuracy: 81.2016%
Val Accuracy: 63.70%
Val F1 Score: 69.18%
Val Precision: 59.78%
Val Recall: 82.09%

100%|██████████| 5/5 [00:00<00:00,  5.47it/s]

Epoch: 121    Loss: 0.3267009645700455    Accuracy: 84.6899%
Val Accuracy: 70.37%
Val F1 Score: 69.70%
Val Precision: 70.77%
Val Recall: 68.66%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 122    Loss: 0.31400215029716494    Accuracy: 84.8837%
Val Accuracy: 64.44%
Val F1 Score: 68.42%
Val Precision: 61.18%
Val Recall: 77.61%

100%|██████████| 5/5 [00:00<00:00,  5.43it/s]

Epoch: 123    Loss: 0.31317140758037565    Accuracy: 84.8837%
Val Accuracy: 69.63%
Val F1 Score: 70.50%
Val Precision: 68.06%
Val Recall: 73.13%

100%|██████████| 5/5 [00:00<00:00,  5.43it/s]

Epoch: 124    Loss: 0.30502826273441314    Accuracy: 85.8527%
Val Accuracy: 64.44%
Val F1 Score: 69.62%
Val Precision: 60.44%
Val Recall: 82.09%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 125    Loss: 0.42801286578178405    Accuracy: 85.6589%
Val Accuracy: 71.85%
Val F1 Score: 67.80%
Val Precision: 78.43%
Val Recall: 59.70%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 126    Loss: 0.4404457449913025    Accuracy: 78.2946%
Val Accuracy: 59.26%
Val F1 Score: 68.57%
Val Precision: 55.56%
Val Recall: 89.55%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 127    Loss: 0.45294123888015747    Accuracy: 79.4574%
Val Accuracy: 60.00%
Val F1 Score: 67.47%
Val Precision: 56.57%
Val Recall: 83.58%

100%|██████████| 5/5 [00:00<00:00,  5.43it/s]

Epoch: 128    Loss: 0.34724011123180387    Accuracy: 83.3333%
Val Accuracy: 70.37%
Val F1 Score: 70.59%
Val Precision: 69.57%
Val Recall: 71.64%

100%|██████████| 5/5 [00:00<00:00,  5.49it/s]

Epoch: 129    Loss: 0.36444604992866514    Accuracy: 83.9147%
Val Accuracy: 70.37%
Val F1 Score: 71.83%
Val Precision: 68.00%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.26it/s]

Epoch: 130    Loss: 0.3169217735528946    Accuracy: 84.6899%
Val Accuracy: 65.19%
Val F1 Score: 71.17%
Val Precision: 60.42%
Val Recall: 86.57%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 131    Loss: 0.31689628660678865    Accuracy: 83.5271%
Val Accuracy: 71.85%
Val F1 Score: 72.46%
Val Precision: 70.42%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.36it/s]

Epoch: 132    Loss: 0.3100915998220444    Accuracy: 84.8837%
Val Accuracy: 73.33%
Val F1 Score: 73.91%
Val Precision: 71.83%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.38it/s]

Epoch: 133    Loss: 0.4490067720413208    Accuracy: 85.8527%
Val Accuracy: 76.30%
Val F1 Score: 73.77%
Val Precision: 81.82%
Val Recall: 67.16%

100%|██████████| 5/5 [00:00<00:00,  5.40it/s]

Epoch: 134    Loss: 0.3681726574897766    Accuracy: 83.5271%
Val Accuracy: 70.37%
Val F1 Score: 71.43%
Val Precision: 68.49%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.35it/s]

Epoch: 135    Loss: 0.32954015135765075    Accuracy: 87.2093%
Val Accuracy: 57.78%
Val F1 Score: 69.19%
Val Precision: 54.24%
Val Recall: 95.52%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 136    Loss: 0.42932785749435426    Accuracy: 73.6434%
Val Accuracy: 69.63%
Val F1 Score: 58.59%
Val Precision: 90.62%
Val Recall: 43.28%

100%|██████████| 5/5 [00:00<00:00,  5.29it/s]

Epoch: 137    Loss: 0.5118187159299851    Accuracy: 76.1628%
Val Accuracy: 59.26%
Val F1 Score: 69.61%
Val Precision: 55.26%
Val Recall: 94.03%

100%|██████████| 5/5 [00:00<00:00,  5.31it/s]

Epoch: 138    Loss: 0.45040873885154725    Accuracy: 76.3566%
Val Accuracy: 60.00%
Val F1 Score: 66.25%
Val Precision: 56.99%
Val Recall: 79.10%

100%|██████████| 5/5 [00:00<00:00,  5.28it/s]

Epoch: 139    Loss: 0.49230384826660156    Accuracy: 83.3333%
Val Accuracy: 70.37%
Val F1 Score: 71.43%
Val Precision: 68.49%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.48it/s]

Epoch: 140    Loss: 0.3455415844917297    Accuracy: 83.5271%
Val Accuracy: 57.04%
Val F1 Score: 67.42%
Val Precision: 54.05%
Val Recall: 89.55%

100%|██████████| 5/5 [00:00<00:00,  5.48it/s]

Epoch: 141    Loss: 0.3589329689741135    Accuracy: 81.5891%
Val Accuracy: 74.81%
Val F1 Score: 73.85%
Val Precision: 76.19%
Val Recall: 71.64%

100%|██████████| 5/5 [00:00<00:00,  5.40it/s]

Epoch: 142    Loss: 0.43323907256126404    Accuracy: 85.2713%
Val Accuracy: 65.19%
Val F1 Score: 71.52%
Val Precision: 60.20%
Val Recall: 88.06%

100%|██████████| 5/5 [00:00<00:00,  5.42it/s]

Epoch: 143    Loss: 0.33489835262298584    Accuracy: 84.1085%
Val Accuracy: 68.15%
Val F1 Score: 71.14%
Val Precision: 64.63%
Val Recall: 79.10%

100%|██████████| 5/5 [00:00<00:00,  5.37it/s]

Epoch: 144    Loss: 0.3374744772911072    Accuracy: 85.8527%
Val Accuracy: 70.37%
Val F1 Score: 71.83%
Val Precision: 68.00%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.34it/s]

Epoch: 145    Loss: 0.2866058379411697    Accuracy: 87.2093%
Val Accuracy: 68.15%
Val F1 Score: 70.34%
Val Precision: 65.38%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 146    Loss: 0.2608592487871647    Accuracy: 87.7907%
Val Accuracy: 66.67%
Val F1 Score: 71.34%
Val Precision: 62.22%
Val Recall: 83.58%

100%|██████████| 5/5 [00:00<00:00,  5.38it/s]

Epoch: 147    Loss: 0.3222968429327011    Accuracy: 87.2093%
Val Accuracy: 75.56%
Val F1 Score: 70.80%
Val Precision: 86.96%
Val Recall: 59.70%

100%|██████████| 5/5 [00:00<00:00,  5.35it/s]

Epoch: 148    Loss: 0.5083423376083374    Accuracy: 82.9457%
Val Accuracy: 71.85%
Val F1 Score: 72.86%
Val Precision: 69.86%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.42it/s]

Epoch: 149    Loss: 0.33760730624198915    Accuracy: 84.4961%
Val Accuracy: 73.33%
Val F1 Score: 73.53%
Val Precision: 72.46%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 150    Loss: 0.2787120044231415    Accuracy: 87.0155%
Val Accuracy: 60.00%
Val F1 Score: 69.32%
Val Precision: 55.96%
Val Recall: 91.04%

100%|██████████| 5/5 [00:00<00:00,  5.43it/s]

Epoch: 151    Loss: 0.3423178970813751    Accuracy: 83.5271%
Val Accuracy: 74.81%
Val F1 Score: 72.13%
Val Precision: 80.00%
Val Recall: 65.67%

100%|██████████| 5/5 [00:00<00:00,  5.40it/s]

Epoch: 152    Loss: 0.3135039880871773    Accuracy: 86.0465%
Val Accuracy: 65.93%
Val F1 Score: 72.62%
Val Precision: 60.40%
Val Recall: 91.04%

100%|██████████| 5/5 [00:00<00:00,  5.41it/s]

Epoch: 153    Loss: 0.2942607820034027    Accuracy: 83.7209%
Val Accuracy: 70.37%
Val F1 Score: 71.83%
Val Precision: 68.00%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.39it/s]

Epoch: 154    Loss: 0.2912550538778305    Accuracy: 87.9845%
Val Accuracy: 74.07%
Val F1 Score: 72.87%
Val Precision: 75.81%
Val Recall: 70.15%

100%|██████████| 5/5 [00:00<00:00,  5.40it/s]

Epoch: 155    Loss: 0.28994865119457247    Accuracy: 87.2093%
Val Accuracy: 73.33%
Val F1 Score: 72.73%
Val Precision: 73.85%
Val Recall: 71.64%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 156    Loss: 0.4432960569858551    Accuracy: 84.4961%
Val Accuracy: 68.89%
Val F1 Score: 70.42%
Val Precision: 66.67%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 157    Loss: 0.3382197320461273    Accuracy: 87.7907%
Val Accuracy: 69.63%
Val F1 Score: 70.07%
Val Precision: 68.57%
Val Recall: 71.64%

100%|██████████| 5/5 [00:00<00:00,  5.30it/s]

Epoch: 158    Loss: 0.27724661529064176    Accuracy: 88.9535%
Val Accuracy: 74.81%
Val F1 Score: 73.02%
Val Precision: 77.97%
Val Recall: 68.66%

100%|██████████| 5/5 [00:00<00:00,  5.49it/s]

Epoch: 159    Loss: 0.29416247010231017    Accuracy: 87.2093%
Val Accuracy: 72.59%
Val F1 Score: 72.59%
Val Precision: 72.06%
Val Recall: 73.13%

100%|██████████| 5/5 [00:00<00:00,  5.46it/s]

Epoch: 160    Loss: 0.2614236414432526    Accuracy: 87.0155%
Val Accuracy: 62.96%
Val F1 Score: 70.59%
Val Precision: 58.25%
Val Recall: 89.55%

100%|██████████| 5/5 [00:00<00:00,  5.36it/s]

Epoch: 161    Loss: 0.25405597761273385    Accuracy: 86.0465%
Val Accuracy: 75.56%
Val F1 Score: 74.02%
Val Precision: 78.33%
Val Recall: 70.15%

100%|██████████| 5/5 [00:00<00:00,  5.45it/s]

Epoch: 162    Loss: 0.42923939824104307    Accuracy: 87.0155%
Val Accuracy: 68.89%
Val F1 Score: 70.42%
Val Precision: 66.67%
Val Recall: 74.63%

100%|██████████| 5/5 [00:00<00:00,  5.51it/s]

Epoch: 163    Loss: 0.3416512221097946    Accuracy: 87.7907%
Val Accuracy: 72.59%
Val F1 Score: 72.18%
Val Precision: 72.73%
Val Recall: 71.64%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 164    Loss: 0.28417888879776    Accuracy: 88.9535%
Val Accuracy: 63.70%
Val F1 Score: 69.57%
Val Precision: 59.57%
Val Recall: 83.58%

100%|██████████| 5/5 [00:00<00:00,  5.51it/s]

Epoch: 165    Loss: 0.32917681336402893    Accuracy: 85.6589%
Val Accuracy: 72.59%
Val F1 Score: 70.87%
Val Precision: 75.00%
Val Recall: 67.16%

100%|██████████| 5/5 [00:00<00:00,  5.39it/s]

Epoch: 166    Loss: 0.2977519154548645    Accuracy: 89.5349%
Val Accuracy: 69.63%
Val F1 Score: 68.22%
Val Precision: 70.97%
Val Recall: 65.67%

100%|██████████| 5/5 [00:00<00:00,  5.31it/s]

Epoch: 167    Loss: 0.29096710681915283    Accuracy: 83.9147%
Val Accuracy: 62.22%
Val F1 Score: 63.83%
Val Precision: 60.81%
Val Recall: 67.16%

100%|██████████| 5/5 [00:00<00:00,  5.05it/s]

Epoch: 168    Loss: 0.3210378050804138    Accuracy: 86.0465%
Val Accuracy: 65.19%
Val F1 Score: 61.16%
Val Precision: 68.52%
Val Recall: 55.22%

100%|██████████| 5/5 [00:00<00:00,  5.28it/s]

Epoch: 169    Loss: 0.38736861348152163    Accuracy: 84.3023%
Val Accuracy: 52.59%
Val F1 Score: 61.90%
Val Precision: 51.49%
Val Recall: 77.61%

100%|██████████| 5/5 [00:00<00:00,  5.39it/s]

Epoch: 170    Loss: 0.33752387166023257    Accuracy: 86.2403%
Val Accuracy: 67.41%
Val F1 Score: 62.71%
Val Precision: 72.55%
Val Recall: 55.22%

100%|██████████| 5/5 [00:00<00:00,  5.52it/s]

Epoch: 171    Loss: 0.29684374034404754    Accuracy: 85.2713%
Val Accuracy: 61.48%
Val F1 Score: 67.90%
Val Precision: 57.89%
Val Recall: 82.09%

100%|██████████| 5/5 [00:00<00:00,  5.42it/s]

Epoch: 172    Loss: 0.4094257831573486    Accuracy: 84.1085%
Val Accuracy: 65.93%
Val F1 Score: 60.34%
Val Precision: 71.43%
Val Recall: 52.24%

100%|██████████| 5/5 [00:00<00:00,  5.33it/s]

Epoch: 173    Loss: 0.2670774877071381    Accuracy: 87.7907%
Val Accuracy: 61.48%
Val F1 Score: 66.67%
Val Precision: 58.43%
Val Recall: 77.61%

100%|██████████| 5/5 [00:00<00:00,  5.27it/s]

Epoch: 174    Loss: 0.23704175949096679    Accuracy: 88.5659%
Val Accuracy: 67.41%
Val F1 Score: 60.71%
Val Precision: 75.56%
Val Recall: 50.75%

100%|██████████| 5/5 [00:00<00:00,  5.19it/s]

Epoch: 175    Loss: 0.37433982491493223    Accuracy: 86.6279%
Val Accuracy: 65.19%
Val F1 Score: 66.67%
Val Precision: 63.51%
Val Recall: 70.15%

100%|██████████| 5/5 [00:00<00:00,  5.42it/s]

Epoch: 176    Loss: 0.27970615923404696    Accuracy: 87.4031%
Val Accuracy: 67.41%
Val F1 Score: 59.26%
Val Precision: 78.05%
Val Recall: 47.76%

100%|██████████| 5/5 [00:00<00:00,  5.36it/s]

Epoch: 177    Loss: 0.404554146528244    Accuracy: 83.3333%
Val Accuracy: 65.93%
Val F1 Score: 62.30%
Val Precision: 69.09%
Val Recall: 56.72%

100%|██████████| 5/5 [00:00<00:00,  5.50it/s]

Epoch: 178    Loss: 0.3935767412185669    Accuracy: 83.5271%
Val Accuracy: 63.70%
Val F1 Score: 72.00%
Val Precision: 58.33%
Val Recall: 94.03%

100%|██████████| 5/5 [00:00<00:00,  5.35it/s]

Epoch: 179    Loss: 0.46632359623909    Accuracy: 73.8372%
Val Accuracy: 63.70%
Val F1 Score: 67.55%
Val Precision: 60.71%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.42it/s]

Epoch: 180    Loss: 0.49399200081825256    Accuracy: 88.5659%
Val Accuracy: 60.74%
Val F1 Score: 65.81%
Val Precision: 57.95%
Val Recall: 76.12%

100%|██████████| 5/5 [00:00<00:00,  5.44it/s]

Epoch: 181    Loss: 0.38750937581062317    Accuracy: 84.4961%
Val Accuracy: 62.22%
Val F1 Score: 62.77%
Val Precision: 61.43%
Val Recall: 64.18%

100%|██████████| 5/5 [00:00<00:00,  5.43it/s]

Epoch: 182    Loss: 0.41470893025398253    Accuracy: 87.2093%
Val Accuracy: 64.44%
Val F1 Score: 62.50%
Val Precision: 65.57%
Val Recall: 59.70%

100%|██████████| 5/5 [00:00<00:00,  5.37it/s]

Epoch: 183    Loss: 0.31740922927856446    Accuracy: 87.9845%
Val Accuracy: 65.19%
Val F1 Score: 65.69%
Val Precision: 64.29%
Val Recall: 67.16%

100%|██████████| 5/5 [00:00<00:00,  5.39it/s]

Epoch: 184    Loss: 0.25858217775821685    Accuracy: 88.7597%
Val Accuracy: 62.22%
Val F1 Score: 62.77%
Val Precision: 61.43%
Val Recall: 64.18%

100%|██████████| 5/5 [00:00<00:00,  5.46it/s]

Epoch: 185    Loss: 0.3476437270641327    Accuracy: 87.5969%
Val Accuracy: 71.11%
Val F1 Score: 66.67%
Val Precision: 78.00%
Val Recall: 58.21%

  0%|          | 0/5 [00:00<?, ?it/s]

In [ ]:
res = [(i, j) for i, j in zip(result['val_f1'], result['val_acc'])]
print(max(res))

In [ ]:
# import json

# line_list = [EFcgDataset]
# name_list = ['EFcgDataset']

# for i in range(len(line_list)):
#   with open(f"/content/drive/MyDrive/ScamSolidityCodeDetection/plots/{name_list[i]}_{mtype}_{len(hfeats)}.json", "w") as outfile:
#       json.dump(line_list[i], outfile)

In [ ]:
# # importing package
# import matplotlib.pyplot as plt
# import numpy as np
# from scipy.interpolate import make_interp_spline

# def ploting(line_list, name_list, line_type):
#   epoches = range(350)
#   plt.figure(figsize=(10, 10))
#   for i in range(len(line_list)):
#     # plot lines
#     X_Y_Spline = make_interp_spline(epoches, line_list[i][line_type])
#     X_ = np.linspace(min(epoches), max(epoches), 50000)
#     Y_ = X_Y_Spline(X_)

#     plt.plot(X_, Y_, label = name_list[i])
#   plt.legend()
#   plt.show()

# ploting([EFcgDataset], ['EFcgDataset - GAT - 2'], 'val_f1')

In [ ]:
# # (0.852112676056338, 0.8775510204081632)
# res = [(i, j) for i, j in zip(EFcgDataset['val_f1'], EFcgDataset['val_acc'])]

# print(max(res))

# Checking

In [ ]:
# !mkdir  /content/drive/MyDrive/ScamSolidityCodeDetection/EFcgDataset/ZippedNonScam
# !mkdir  /content/drive/MyDrive/ScamSolidityCodeDetection/EFcgDataset/ZippedScam

In [ ]:
# # !zip -r /content/drive/MyDrive/ScamSolidityCodeDetection/EFcgDataset/ZippedNonScam/EFcgDataset_NonScam.zip /content/drive/MyDrive/ScamSolidityCodeDetection/EFcgDataset/NonScam
# !zip -r /content/drive/MyDrive/ScamSolidityCodeDetection/EFcgDataset/ZippedScam/EFcgDataset_Scam.zip /content/drive/MyDrive/ScamSolidityCodeDetection/EFcgDataset/Scam

In [ ]:
# import os
# import json
# # quangnguyen11037 benign (1 - 13)
# # quangnguyen2910 benign (14 - 25)
# # quangnm711 malware (full)

# dictionary = {
#   "title": f"Sol_Dataset_EFcg_NonScam",
#   "id": f"quangnguyen11037/sol-dataset-efcg-nonscam",
#   "licenses": [
#     {
#       "name": "CC0-1.0"
#     }
#   ]
# }

# # Serializing json
# json_object = json.dumps(dictionary, indent=2)

# # Writing to sample.json
# with open(f"/content/drive/MyDrive/ScamSolidityCodeDetection/EFcgDataset/ZippedNonScam/dataset-metadata.json", "w") as outfile:
#     outfile.write(json_object)

# dictionary = {
#   "title": f"Sol_Dataset_EFcg_Scam",
#   "id": f"quangnguyen11037/sol-dataset-efcg-scam",
#   "licenses": [
#     {
#       "name": "CC0-1.0"
#     }
#   ]
# }

# # Serializing json
# json_object = json.dumps(dictionary, indent=2)

# # Writing to sample.json
# with open(f"/content/drive/MyDrive/ScamSolidityCodeDetection/EFcgDataset/ZippedScam/dataset-metadata.json", "w") as outfile:
#     outfile.write(json_object)

In [ ]:
# os.environ['KAGGLE_CONFIG_DIR'] = "/content/quangnguyen11037"

In [ ]:
# !chmod 600 /content/quangnguyen11037/kaggle.json

In [ ]:
# !kaggle datasets create -p /content/drive/MyDrive/ScamSolidityCodeDetection/EFcgDataset/ZippedNonScam --dir-mode skip --public
# !kaggle datasets create -p /content/drive/MyDrive/ScamSolidityCodeDetection/EFcgDataset/ZippedScam --dir-mode skip --public